version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: clicker
      POSTGRES_PASSWORD: clicker
      POSTGRES_DB: clicker
    ports:
      - "5400:5432"  # host:container
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: clicker-backend
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: clicker
      DB_PASSWORD: clicker
      DB_NAME: clicker


  frontend:
    build: ./frontend
    container_name: clicker-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
